package cmd

import (
	"VideoTranscode/service"
	"VideoTranscode/service/process"
	"errors"

	"github.com/spf13/cobra"
)

var TsCmd = &cobra.Command{
	Use:   "ts",
	Short: "TS stream file processing utilities",
	Long: `Process TS transport‑stream files, support generating concat list file and merging ts segments.

Examples:
  VideoTranscode ts list ./segments/ filelist.txt
  VideoTranscode ts merge filelist.txt output.mp4
`,
	Args: func(cmd *cobra.Command, args []string) error {
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	},
}

var TsListCmd = &cobra.Command{
	Use:   "list <input‑dir> <output‑list>",
	Short: "Generate ffmpeg concat list from ts directory",
	Long: `Scan directory and generate ffmpeg‑style concat text list for ts segments.
The output list file can be used for ts merge operation.

Example:
  VideoTranscode ts list ./ts_dir filelist.txt
`,
	Args: func(cmd *cobra.Command, args []string) error {
		if len(args) != 2 {
			return errors.New("requires exactly 2 arguments: <input‑directory> <output‑list‑file>")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := service.CheckFFTools(); err != nil {
			return err
		}
		obj := process.TsList{
			ConversionConfig: service.ConversionConfig{
				InputFile:  args[0],
				OutputFile: args[1],
			},
		}
		return obj.Convert()
	},
}

var TsMergeCmd = &cobra.Command{
	Use:   "merge <concat‑list> <output>",
	Short: "Merge multiple ts segments into one media file",
	Long: `Merge ts segments using ffmpeg concat demuxer.
Input is the concat list file generated by "ts list" command.
Supports output formats such as mp4, mpeg, ts.

Example:
  VideoTranscode ts merge filelist.txt output.mp4
`,
	Args: func(cmd *cobra.Command, args []string) error {
		if len(args) != 2 {
			return errors.New("requires exactly 2 arguments: <concat‑list‑file> <output‑file>")
		}
		return nil
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := service.CheckFFTools(); err != nil {
			return err
		}
		obj := process.TsMerge{
			ConversionConfig: service.ConversionConfig{
				InputFile:  args[0],
				OutputFile: args[1],
			},
		}
		return obj.Convert()
	},
}

func init() {
	TsCmd.AddCommand(TsListCmd)
	TsCmd.AddCommand(TsMergeCmd)
}
